import mongoose from 'mongoose';
import type { Snapshot } from '../types/schemas';

/* This file has been mostly generated by AI */

const snapshotDbSchema = new mongoose.Schema<Snapshot>(
  {
    date: { type: String, required: true, unique: true },
    tracks: { type: mongoose.Schema.Types.Mixed, required: true },
  },
  { versionKey: false, timestamps: { createdAt: true, updatedAt: false } }
);

snapshotDbSchema.index({ createdAt: 1 }, { expireAfterSeconds: 60 * 60 * 24 * 365 });

export const SnapshotModel =
  (mongoose.models.Snapshot as mongoose.Model<Snapshot> | undefined) ??
  mongoose.model<Snapshot>('Snapshot', snapshotDbSchema);
