import mongoose from 'mongoose';
import type { Snapshot } from '../types/schemas';

/* This file has been mostly generated by AI */

const snapshotDbSchema = new mongoose.Schema<Snapshot>(
  {
    date: { type: String, required: true, unique: true },
    tracks: { type: mongoose.Schema.Types.Mixed, required: true },
  },
  { versionKey: false }
);

export const SnapshotModel =
  (mongoose.models.Snapshot as mongoose.Model<Snapshot> | undefined) ??
  mongoose.model<Snapshot>('Snapshot', snapshotDbSchema);
