export const env = {
  RENDER_BASE_URL: process.env.RENDER_BASE_URL!,
  REDIRECT_URI: process.env.REDIRECT_URI!,
  SPOTIFY_CLIENT_ID: process.env.SPOTIFY_CLIENT_ID!,
  SPOTIFY_CLIENT_SECRET: process.env.SPOTIFY_CLIENT_SECRET!,
  SPOTIFY_ADMIN_USERNAME: process.env.SPOTIFY_ADMIN_USERNAME,
  REDIS_KEY_REFRESH_TOKEN: process.env.REDIS_KEY_REFRESH_TOKEN!,
  REDIS_URL: process.env.REDIS_URL!,
};
