name: Daily Cron to Cache Trending Last.fm Tracks

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  cold-start:
    timeout-minutes: 10
    runs-on: ubuntu-24.04
    steps:
    - name: Wake up service and verify availability via cURL
      uses: jtalk/url-health-check-action@v4
      with:
        url: ${{ secrets.BASE_URL }}
        max-attempts: 10
        retry-delay: 20s

  cache-tracks:
    needs: cold-start
    timeout-minutes: 5
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-node@v6
      with:
        node-version: 24
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run script to call API and store fetched JSON in Redis
      run: npx tsx app/lib/scripts/storeTracks.ts
      env:
        LASTFM_API_KEY: ${{ secrets.LASTFM_API_KEY }}
        REDIS_URL: ${{ secrets.REDIS_URL }}

    - name: Run script to revalidate homepage ISR cache
      run: npx tsx app/lib/scripts/revalidateHome.ts
      env:
        REVALIDATION_SECRET: ${{ secrets.REVALIDATION_SECRET }}
        BASE_URL: ${{ secrets.BASE_URL }}
